import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const categories = [
  { id: "plumbing",     name: "Plumbing",         icon: "🔧", description: "Pipe repairs, leak fixes, installations", color: "text-blue-600",    bgColor: "bg-blue-50",    count: 234, subcategories: ["Pipe Repair","Leak Detection","Drain Cleaning","Water Heater","Bathroom Remodel","Fixture Install"] },
  { id: "electrical",   name: "Electrical",        icon: "⚡", description: "Wiring, panels, outlets, smart home",     color: "text-yellow-600",  bgColor: "bg-yellow-50",  count: 189, subcategories: ["Panel Upgrade","Outlet Install","Wiring","EV Charger","Smart Home","Lighting"] },
  { id: "hvac",         name: "HVAC",              icon: "❄️", description: "AC, heating, ventilation services",       color: "text-cyan-600",    bgColor: "bg-cyan-50",    count: 156, subcategories: ["AC Repair","Furnace Repair","Duct Cleaning","Installation","Maintenance","Air Quality"] },
  { id: "cleaning",     name: "Cleaning",          icon: "🧹", description: "Home, office, deep and move-out cleaning",color: "text-green-600",   bgColor: "bg-green-50",   count: 412, subcategories: ["Deep Clean","Regular Clean","Move-Out","Office Clean","Carpet Clean","Window Wash"] },
  { id: "landscaping",  name: "Landscaping",       icon: "🌿", description: "Lawn care, garden design, tree services", color: "text-emerald-600", bgColor: "bg-emerald-50", count: 178, subcategories: ["Lawn Mowing","Garden Design","Tree Trimming","Irrigation","Leaf Removal","Planting"] },
  { id: "painting",     name: "Painting",          icon: "🎨", description: "Interior and exterior painting services",  color: "text-purple-600",  bgColor: "bg-purple-50",  count: 143, subcategories: ["Interior Paint","Exterior Paint","Cabinet Painting","Deck Staining","Wallpaper","Touch-Up"] },
  { id: "carpentry",    name: "Carpentry",         icon: "🪚", description: "Custom furniture, repairs, renovations",  color: "text-amber-600",   bgColor: "bg-amber-50",   count: 98,  subcategories: ["Custom Build","Furniture Repair","Decking","Framing","Crown Molding","Door Install"] },
  { id: "roofing",      name: "Roofing",           icon: "🏠", description: "Roof repair, replacement, gutters",       color: "text-red-600",     bgColor: "bg-red-50",     count: 87,  subcategories: ["Roof Repair","Replacement","Gutter Install","Inspection","Leak Repair","Shingle Replace"] },
  { id: "flooring",     name: "Flooring",          icon: "🪵", description: "Hardwood, tile, carpet installation",     color: "text-orange-600",  bgColor: "bg-orange-50",  count: 112, subcategories: ["Hardwood","Tile","Carpet","Vinyl","Refinishing","Subfloor Repair"] },
  { id: "moving",       name: "Moving",            icon: "📦", description: "Local and long-distance moving help",     color: "text-indigo-600",  bgColor: "bg-indigo-50",  count: 203, subcategories: ["Local Move","Long Distance","Packing","Furniture Assembly","Storage","Piano Move"] },
  { id: "pest-control", name: "Pest Control",      icon: "🐛", description: "Extermination and prevention services",  color: "text-lime-600",    bgColor: "bg-lime-50",    count: 76,  subcategories: ["Rodent Control","Termite","Bed Bugs","Ant Control","Cockroach","Mosquito"] },
  { id: "appliance",    name: "Appliances",        icon: "🍳", description: "Repair and installation of appliances",  color: "text-gray-600",    bgColor: "bg-gray-50",    count: 134, subcategories: ["Washer Repair","Dryer Repair","Dishwasher","Refrigerator","Oven Repair","Microwave"] },
  { id: "auto",         name: "Auto Services",     icon: "🚗", description: "Car wash, detailing, minor repairs",     color: "text-slate-600",   bgColor: "bg-slate-50",   count: 89,  subcategories: ["Car Wash","Detailing","Oil Change","Tire Change","Dent Removal","Battery Replace"] },
  { id: "pet",          name: "Pet Care",          icon: "🐾", description: "Dog walking, grooming, pet sitting",     color: "text-pink-600",    bgColor: "bg-pink-50",    count: 267, subcategories: ["Dog Walking","Pet Sitting","Grooming","Training","Vet Transport","Boarding"] },
  { id: "tech",         name: "Tech Support",      icon: "💻", description: "Computer repair, network, smart home",   color: "text-blue-700",    bgColor: "bg-blue-50",    count: 145, subcategories: ["Computer Repair","Network Setup","Smart Home","Data Recovery","Phone Repair","Virus Removal"] },
  { id: "wellness",     name: "Wellness",          icon: "💆", description: "Massage, yoga, personal training",       color: "text-teal-600",    bgColor: "bg-teal-50",    count: 198, subcategories: ["Massage","Personal Training","Yoga","Nutrition","Meditation","Physical Therapy"] },
  { id: "tutoring",     name: "Tutoring",          icon: "📚", description: "Academic tutoring and test prep",        color: "text-violet-600",  bgColor: "bg-violet-50",  count: 223, subcategories: ["Math","Science","English","SAT/ACT Prep","Languages","Music Lessons"] },
  { id: "photography",  name: "Photography",       icon: "📷", description: "Events, portraits, real estate photos",  color: "text-rose-600",    bgColor: "bg-rose-50",    count: 112, subcategories: ["Event Photography","Portrait","Real Estate","Product","Wedding","Headshots"] },
  { id: "security",     name: "Home Security",     icon: "🔒", description: "Alarm systems, cameras, smart locks",    color: "text-gray-700",    bgColor: "bg-gray-50",    count: 67,  subcategories: ["Camera Install","Alarm System","Smart Lock","Motion Sensors","Access Control","Monitoring"] },
  { id: "childcare",    name: "Childcare",         icon: "👶", description: "Babysitting, nanny, after-school care",  color: "text-yellow-500",  bgColor: "bg-yellow-50",  count: 156, subcategories: ["Babysitting","Nanny","After School","Tutoring","Special Needs","Overnight"] },
  { id: "elder-care",   name: "Elder Care",        icon: "👴", description: "Companion care, errands, medical assist",color: "text-blue-500",    bgColor: "bg-blue-50",    count: 89,  subcategories: ["Companion Care","Errands","Medication Remind","Transportation","Meal Prep","Light Housekeeping"] },
  { id: "legal",        name: "Legal Help",        icon: "⚖️", description: "Document review, notary, consultations",color: "text-gray-800",    bgColor: "bg-gray-50",    count: 45,  subcategories: ["Notary","Document Review","Legal Consultation","Will Prep","Contract Review","Small Claims"] },
  { id: "finance",      name: "Finance",           icon: "💰", description: "Tax prep, bookkeeping, financial advice",color: "text-green-700",   bgColor: "bg-green-50",   count: 78,  subcategories: ["Tax Preparation","Bookkeeping","Financial Planning","Payroll","Budget Help","Accounting"] },
  { id: "event",        name: "Event Planning",    icon: "🎉", description: "Party planning, catering, entertainment",color: "text-fuchsia-600", bgColor: "bg-fuchsia-50", count: 134, subcategories: ["Party Planning","Catering","DJ","Bartending","Decorating","Photo Booth"] },
  { id: "beauty",       name: "Beauty",            icon: "💅", description: "Hair, nails, makeup, skincare at home",  color: "text-pink-500",    bgColor: "bg-pink-50",    count: 189, subcategories: ["Haircut","Nail Service","Makeup","Waxing","Facials","Eyelash Extensions"] },
];

const providers = [
  { id:"p1",  name:"Marcus Johnson",   avatar:"MJ", categoryId:"plumbing",     subcategory:"Pipe Repair",    rating:4.9, reviewCount:312, hourlyRate:85,  bio:"Licensed master plumber with 15 years of experience. Specializing in emergency repairs, leak detection, and full bathroom remodels.",                    location:"New York, NY",      experience:15, completedJobs:1240, responseTime:"~15 min", verified:true, badges:["Top Rated","Quick Response","Licensed"],              availability:["Mon","Tue","Wed","Thu","Fri","Sat"],     online:true,  distanceKm:1.2, acceptanceRate:96, portfolio:[],
    reviews:[{id:"r1",author:"Sarah K.",  avatar:"SK",rating:5,comment:"Marcus was amazing! Fixed our burst pipe at 2am without any fuss.",        date:"2 days ago",  service:"Emergency Pipe Repair"},{id:"r2",author:"Tom R.",   avatar:"TR",rating:5,comment:"Professional, clean, and on time. Best plumber I've hired.",               date:"1 week ago",  service:"Leak Detection"},{id:"r3",author:"Lisa M.",  avatar:"LM",rating:4,comment:"Great work on our bathroom remodel. Minor delay but excellent quality.",   date:"2 weeks ago", service:"Bathroom Remodel"}]},
  { id:"p2",  name:"Emily Chen",       avatar:"EC", categoryId:"electrical",   subcategory:"Panel Upgrade",  rating:4.8, reviewCount:189, hourlyRate:95,  bio:"Certified electrician specializing in panel upgrades, smart home installations, and EV charger setups. Safety-first approach with all work up to code.", location:"Los Angeles, CA",    experience:10, completedJobs:890,  responseTime:"~30 min", verified:true, badges:["Top Rated","Certified","Background Checked"],         availability:["Mon","Tue","Wed","Thu","Fri"],           online:true,  distanceKm:2.8, acceptanceRate:91, portfolio:[],
    reviews:[{id:"r4",author:"David L.", avatar:"DL",rating:5,comment:"Emily installed our EV charger and smart home system flawlessly.",          date:"3 days ago",  service:"EV Charger Install"},{id:"r5",author:"Maria S.", avatar:"MS",rating:5,comment:"Upgraded our panel safely and efficiently. Very professional.",            date:"1 week ago",  service:"Panel Upgrade"}]},
  { id:"p3",  name:"James Williams",   avatar:"JW", categoryId:"hvac",         subcategory:"AC Repair",      rating:4.7, reviewCount:256, hourlyRate:90,  bio:"HVAC technician with EPA certification. Expert in all major brands of AC, heating, and ventilation systems. Emergency services available.",             location:"Chicago, IL",       experience:12, completedJobs:1100, responseTime:"~20 min", verified:true, badges:["EPA Certified","Quick Response","Insured"],           availability:["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],online:true,  distanceKm:0.9, acceptanceRate:88, portfolio:[],
    reviews:[{id:"r6",author:"Bob T.",   avatar:"BT",rating:5,comment:"Fixed our AC in the middle of a heat wave. True lifesaver!",                date:"1 day ago",   service:"AC Repair"},{id:"r7",author:"Anna P.",  avatar:"AP",rating:4,comment:"Good work on the furnace. Explained everything clearly.",                    date:"5 days ago",  service:"Furnace Repair"}]},
  { id:"p4",  name:"Sofia Rodriguez",  avatar:"SR", categoryId:"cleaning",     subcategory:"Deep Clean",     rating:5.0, reviewCount:428, hourlyRate:55,  bio:"Professional cleaning specialist with a 5-star record. Using eco-friendly products, deep cleaning, move in/out cleaning, and regular maintenance.",    location:"Miami, FL",         experience:8,  completedJobs:2100, responseTime:"~10 min", verified:true, badges:["Top Rated","Eco-Friendly","Background Checked"],      availability:["Mon","Tue","Wed","Thu","Fri","Sat"],     online:true,  distanceKm:3.1, acceptanceRate:98, portfolio:[],
    reviews:[{id:"r8",author:"Jenny W.", avatar:"JW",rating:5,comment:"Sofia transformed our apartment! Absolutely spotless. Will book again.",    date:"2 days ago",  service:"Deep Clean"},{id:"r9",author:"Carlos M.",avatar:"CM",rating:5,comment:"Best cleaning service I've ever used. Worth every penny.",             date:"4 days ago",  service:"Move-Out Cleaning"}]},
  { id:"p5",  name:"David Park",       avatar:"DP", categoryId:"landscaping",  subcategory:"Lawn Mowing",    rating:4.8, reviewCount:167, hourlyRate:60,  bio:"Landscape professional creating beautiful outdoor spaces. From lawn maintenance to full garden design. Fully insured and licensed.",                    location:"Seattle, WA",       experience:7,  completedJobs:780,  responseTime:"~25 min", verified:true, badges:["Licensed","Insured","Design Expert"],                 availability:["Mon","Wed","Thu","Fri","Sat"],           online:false, distanceKm:4.5, acceptanceRate:85, portfolio:[],
    reviews:[{id:"r10",author:"Rachel B.",avatar:"RB",rating:5,comment:"David completely transformed our backyard. It looks incredible!",           date:"1 week ago",  service:"Garden Design"}]},
  { id:"p6",  name:"Aisha Thompson",   avatar:"AT", categoryId:"painting",     subcategory:"Interior Paint", rating:4.9, reviewCount:203, hourlyRate:70,  bio:"Professional painter with an eye for detail. Interior and exterior painting, cabinet refinishing, and decorative finishes. Always on schedule.",          location:"Houston, TX",       experience:9,  completedJobs:950,  responseTime:"~45 min", verified:true, badges:["Top Rated","Detail-Oriented","Insured"],              availability:["Mon","Tue","Wed","Thu","Fri"],           online:true,  distanceKm:2.2, acceptanceRate:93, portfolio:[],
    reviews:[{id:"r11",author:"Mike H.", avatar:"MH",rating:5,comment:"Aisha painted our whole house and it looks brand new. Incredible detail.",  date:"3 days ago",  service:"Interior Painting"}]},
  { id:"p7",  name:"Ryan O'Brien",     avatar:"RO", categoryId:"carpentry",    subcategory:"Custom Build",   rating:4.8, reviewCount:142, hourlyRate:80,  bio:"Master carpenter crafting custom furniture, built-ins, and renovations. Combining traditional craftsmanship with modern design for unique pieces.",       location:"Boston, MA",        experience:18, completedJobs:620,  responseTime:"~1 hour", verified:true, badges:["Master Craftsman","Custom Work","Licensed"],          availability:["Mon","Tue","Thu","Fri","Sat"],           online:false, distanceKm:5.7, acceptanceRate:82, portfolio:[],
    reviews:[{id:"r12",author:"Nancy F.", avatar:"NF",rating:5,comment:"Ryan built us a stunning custom bookshelf. The craftsmanship is phenomenal.",date:"2 weeks ago", service:"Custom Shelving"}]},
  { id:"p8",  name:"Lisa Nguyen",      avatar:"LN", categoryId:"pet",          subcategory:"Dog Walking",    rating:5.0, reviewCount:389, hourlyRate:30,  bio:"Certified pet care professional and animal lover. Dog walking, pet sitting, grooming, and training. Your furry family members are in the best hands!",  location:"San Francisco, CA", experience:6,  completedJobs:1800, responseTime:"~5 min",  verified:true, badges:["Top Rated","Certified","Insured","Pet First Aid"],    availability:["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],online:true,  distanceKm:0.6, acceptanceRate:99, portfolio:[],
    reviews:[{id:"r13",author:"Sam K.",  avatar:"SK",rating:5,comment:"Lisa is amazing with our dog! He gets so excited when she comes.",           date:"1 day ago",   service:"Dog Walking"}]},
  { id:"p9",  name:"Kevin Patel",      avatar:"KP", categoryId:"tech",         subcategory:"Smart Home",     rating:4.9, reviewCount:178, hourlyRate:75,  bio:"IT professional and smart home specialist. Computer repairs, network setup, smart device installation, and security systems. Same-day service available.", location:"Austin, TX",         experience:11, completedJobs:820,  responseTime:"~20 min", verified:true, badges:["Certified Tech","Smart Home Expert","Background Checked"],availability:["Mon","Tue","Wed","Thu","Fri","Sat"], online:true,  distanceKm:1.8, acceptanceRate:94, portfolio:[],
    reviews:[{id:"r14",author:"Helen J.", avatar:"HJ",rating:5,comment:"Kevin set up our entire smart home system. Absolutely seamless.",           date:"5 days ago",  service:"Smart Home Setup"}]},
  { id:"p10", name:"Priya Sharma",     avatar:"PS", categoryId:"wellness",     subcategory:"Massage",        rating:4.9, reviewCount:267, hourlyRate:90,  bio:"Licensed massage therapist with expertise in Swedish, deep tissue, and sports massage. Mobile service — I come to your home.",                           location:"Denver, CO",        experience:5,  completedJobs:980,  responseTime:"~30 min", verified:true, badges:["Licensed","Mobile Service","Background Checked"],     availability:["Tue","Wed","Thu","Fri","Sat","Sun"],     online:true,  distanceKm:3.4, acceptanceRate:90, portfolio:[],
    reviews:[{id:"r15",author:"Chris D.", avatar:"CD",rating:5,comment:"Best massage I've ever had. Priya is incredibly skilled and professional.",  date:"3 days ago",  service:"Deep Tissue Massage"}]},
  { id:"p11", name:"Omar Hassan",      avatar:"OH", categoryId:"roofing",      subcategory:"Roof Repair",    rating:4.7, reviewCount:98,  hourlyRate:100, bio:"Licensed roofing contractor with 14 years of experience. Specializing in emergency repairs, full replacements, and gutter systems. Free inspections.",   location:"Phoenix, AZ",       experience:14, completedJobs:540,  responseTime:"~1 hour", verified:true, badges:["Licensed","Insured","Free Inspection"],               availability:["Mon","Tue","Wed","Thu","Fri"],           online:false, distanceKm:6.2, acceptanceRate:80, portfolio:[],
    reviews:[{id:"r16",author:"Patricia L.",avatar:"PL",rating:5,comment:"Omar fixed our roof after a storm quickly and at a fair price.",          date:"1 week ago",  service:"Storm Damage Repair"}]},
  { id:"p12", name:"Grace Kim",        avatar:"GK", categoryId:"tutoring",     subcategory:"Math",           rating:5.0, reviewCount:334, hourlyRate:65,  bio:"Former teacher turned private tutor. Specializing in K-12 math, SAT/ACT prep, and calculus. Proven track record of improving grades.",                  location:"New York, NY",      experience:8,  completedJobs:1450, responseTime:"~10 min", verified:true, badges:["Top Rated","Certified Teacher","Background Checked"], availability:["Mon","Tue","Wed","Thu","Fri","Sat"],     online:true,  distanceKm:2.0, acceptanceRate:97, portfolio:[],
    reviews:[{id:"r17",author:"Parent of Alex",avatar:"PA",rating:5,comment:"Grace helped my son go from a C to an A in calculus in 2 months.",    date:"4 days ago",  service:"High School Math"}]},
];

async function main() {
  console.log("Seeding categories...");
  for (const cat of categories) {
    await prisma.category.upsert({ where: { id: cat.id }, update: cat, create: cat });
  }

  console.log("Seeding providers and reviews...");
  for (const { reviews, ...p } of providers) {
    await prisma.provider.upsert({ where: { id: p.id }, update: p, create: p });
    for (const r of reviews) {
      await prisma.review.upsert({
        where: { id: r.id },
        update: { ...r, providerId: p.id },
        create: { ...r, providerId: p.id },
      });
    }
  }

  console.log(`Done. ${categories.length} categories, ${providers.length} providers seeded.`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
